# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e52dfe7a1b7aea4ae33884f1a8820e0a1c76b7e2f8ee6de51291ed2f4a5b4baf66edde978ed4336ee227189903106fe003c64510078f0598f5eaaaa674581f6

test:
  secret_key_base: 4f9d2b3ae5721e9aba0a07459dd4e4f9cfecda66ec1a6602a8e7f3c26e65af663ca4ed1a27640cac2900ff0339bd5316c9e0f0c64e8f1e67b2c15f902ab05375

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
